# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thothica < Formula
  desc "A simple cli tool to manage semantic search"
  homepage "https://github.com/Thothica/thothica"
  version "0.1.02"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Thothica/thothica/releases/download/v0.1.02/thothica_Darwin_x86_64.tar.gz"
      sha256 "fa0c8dbc719036cba452ed90c7274691cfac779b898d18a146b66ba6033df837"

      def install
        bin.install "thothica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Thothica/thothica/releases/download/v0.1.02/thothica_Darwin_arm64.tar.gz"
      sha256 "fc61546949185f01bd82ab19309bf2274fcedd6510a8580eef37b8ecbf27a39a"

      def install
        bin.install "thothica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Thothica/thothica/releases/download/v0.1.02/thothica_Linux_x86_64.tar.gz"
      sha256 "d609dd4fbf874990f1cc4bba4bacdba6a166feaca9388f1d68237be18ddd0848"

      def install
        bin.install "thothica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thothica/thothica/releases/download/v0.1.02/thothica_Linux_arm64.tar.gz"
      sha256 "4214675565df7ec0239c93fcb675598a343fe73f5694dae9f0ff3d1125617c42"

      def install
        bin.install "thothica"
      end
    end
  end

  def caveats
    <<~EOS
      You need to create a .thothica file in $HOME directory
    EOS
  end
end
